In [2]:
from transformers import AutoModelForCausalLM,AutoTokenizer,RobertaForSequenceClassification

/data/xzb/miniconda3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
model = AutoModelForCausalLM.from_pretrained('/data/xzb/models/Qwen2.5-0.5B').half()

In [5]:
model2 = AutoModelForCausalLM.from_pretrained('/data/xzb/models/llama3.2-1B/').half()

In [7]:
print(model2.config)

LlamaConfig {
  "_attn_implementation_autoset": true,
  "_name_or_path": "/data/xzb/models/llama3.2-1B/",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 128000,
  "eos_token_id": 128001,
  "head_dim": 64,
  "hidden_act": "silu",
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 131072,
  "mlp_bias": false,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 16,
  "num_key_value_heads": 8,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 32.0,
    "high_freq_factor": 4.0,
    "low_freq_factor": 1.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },
  "rope_theta": 500000.0,
  "tie_word_embeddings": true,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.46.3",
  "use_cache": true,
  "vocab_size": 128256
}



In [8]:
print(model.config)

Qwen2Config {
  "_attn_implementation_autoset": true,
  "_name_or_path": "/data/xzb/models/Qwen2.5-0.5B",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": true,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.46.3",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}



In [9]:
print(model)

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 896)
    (layers): ModuleList(
      (0-23): 24 x Qwen2DecoderLayer(
        (self_attn): Qwen2SdpaAttention(
          (q_proj): Linear(in_features=896, out_features=896, bias=True)
          (k_proj): Linear(in_features=896, out_features=128, bias=True)
          (v_proj): Linear(in_features=896, out_features=128, bias=True)
          (o_proj): Linear(in_features=896, out_features=896, bias=False)
          (rotary_emb): Qwen2RotaryEmbedding()
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear(in_features=896, out_features=4864, bias=False)
          (up_proj): Linear(in_features=896, out_features=4864, bias=False)
          (down_proj): Linear(in_features=4864, out_features=896, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((896,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((

In [3]:
import torch
mask = torch.load("/data/xzb/fedsn/save_models/20241113e2e/gpt2_medium_e2e_p1(0.0)p2(0.0)_R10_N25C5_localepochs1_time_20241113144141/server_mask.pth")

/tmp/ipykernel_375896/478651214.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  mask = torch.load("/data/xzb/fedsn/save_models/20241113e2e/gpt2_medium_e2e_p1(0.0)p2(0.0)

In [4]:
print(mask)

{'emb': array([1., 1., 1., ..., 1., 1., 1.]), 'attn': array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]]), 'mlp': array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])}


In [3]:
print(model)

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 1280)
    (wpe): Embedding(1024, 1280)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-35): 36 x GPT2Block(
        (ln_1): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((1280,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=1280, out_features=50257, bias=False)
)


In [9]:
model = RobertaForSequenceClassification.from_pretrained('/home/xzb/models/roberta_base').to('cuda:1')

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at /home/xzb/models/roberta_base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [12]:
print(model.config)

RobertaConfig {
  "_name_or_path": "/home/xzb/models/roberta_base",
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "transformers_version": "4.39.1",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}



In [15]:
import numpy as np
p1 = 0.1
n_embd = 10

In [33]:
np.array([[2,2,2,2,2,2,2,2,2,2],[3,3,3,3,3,3,3,3,3,3]])*np.random.choice([0, 1/(1-p1)], size=(2,10), p=[p1, 1-p1]),

(array([[2.22222222, 2.22222222, 2.22222222, 2.22222222, 2.22222222,
         2.22222222, 2.22222222, 2.22222222, 2.22222222, 2.22222222],
        [3.33333333, 3.33333333, 3.33333333, 3.33333333, 0.        ,
         3.33333333, 3.33333333, 3.33333333, 3.33333333, 3.33333333]]),)

In [99]:
import numpy as np

def set_10_percent_to_zero_and_scale(arr, p=0.1):
    total_elements = arr.size  # 数组的总元素个数
    num_to_zero = int(p * total_elements)  # 需要置为0的元素总数
    
    # 找到数组中非0元素的索引
    non_zero_indices = np.argwhere(arr != 0)  # 返回的是多维索引的坐标
    
    # 如果非0元素不足以达到 num_to_zero 数量，取非0元素的数量
    num_to_zero = min(num_to_zero, len(non_zero_indices))
    
    # 从非零元素中随机选取 num_to_zero 个进行置零
    selected_indices = np.random.choice(len(non_zero_indices), num_to_zero, replace=False)
    
    # 将选中的元素置为0
    for idx in selected_indices:
        arr[tuple(non_zero_indices[idx])] = 0  # 多维索引需要用 tuple
    
    # 找到未选中的非零元素的索引
    unselected_indices = np.setdiff1d(np.arange(len(non_zero_indices)), selected_indices)
    
    # 对未选中的非零元素进行放大操作
    for idx in unselected_indices:
        arr[tuple(non_zero_indices[idx])] *= 1 / (1 - p)
    
    return arr

# 示例：n维数组 (例如 3维数组)
arr = np.array([[[1, 0, 2], [3, 0, 4]], [[5, 6, 0], [7, 8, 9]]])

# 调用函数，置10%的元素为0并放大其他非零元素
result = set_10_percent_to_zero_and_scale(arr)
print(result)




[[1 0 2 3 0]
 [0 5 6 0 7]]


In [100]:
print(np.array([2,3,4])*np.array([3,2,4]))

[ 6  6 16]
